# Generated by Django 4.2.7 on 2024-09-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Maktab')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon rakami')),
                ('payment', models.BooleanField(blank=True, default=False, null=True, verbose_name='Tolov')),
                ('language', models.CharField(blank=True, max_length=5, null=True, verbose_name='Til')),
            ],
        ),
        migrations.AlterModelOptions(
            name='buttonmod',
            options={'verbose_name': 'ButtonMod', 'verbose_name_plural': 'ButtonMods'},
        ),
    ]
